import Header from "@/app/components/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <footer className="container py-8 text-gray-500">
          <div>
            <div className="mt-8">
              <p>
                Email:{" "}
                <a href="mailto:info@dev-champions.tech" className="underline">
                  info@dev-champions.tech
                </a>
              </p>
              <p>
                Phone:{" "}
                <a href="tel:+2349115034504" className="underline">
                  +234 9115 034 504
                </a>
              </p>
            </div>
          </div>
          <span className="ml-3   font-semibold text-[#077998]">DC </span>
          <span className="text-[#8A1D4F] font-semibold">Jobs</span>&copy; 2025
          - All rights reserved
        </footer>
      </body>
    </html>
  );
}
